#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the countingValleys function below.
#Hypothesis 1 counting valleys = counting the number of 'UD' 
def countingValleys(n, s):
    path = list(s)
    count = 0
    #count = path.count('UD') - doesn't work cause each element of list is U or D not UD
    for i in range (n):
        if path[i]=='U' and path[i-1]=='D':
            count = count +1

    print ('count is: ', count)

    return count

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    s = input()

    result = countingValleys(n, s)

    fptr.write(str(result) + '\n')

    fptr.close()
